Task/backend20 add mail service
BinaryStudioAcademy/bsa-2022-streamlet pull request #10
Opened 2022-08-08 22:50 UTC by nemuzora-nozomu

Beside the mail service, I've also created couple simple mail templates for it which can be changed or added in future.

2022-08-08 22:53 UTC, nemuzora-nozomu commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add send mail service](https://trello.com/c/fjFIr1pz/20-add-send-mail-service)

2022-08-09 09:46 UTC, nemuzora-nozomu commented
something's very wrong 😢
first I was trying to resolve the conflict, then it just removed all my installed dependencies for some reason
trying to revert last commits now

2022-08-09 10:41 UTC, nemuzora-nozomu commented
finally got it to work

2022-08-09 11:45 UTC, VitaliiBedletskyi requested changes

2022-08-09 11:45 UTC, VitaliiBedletskyi commented on backend/src/core/mail/application/mail-service.ts
> +    const transport = await createMailTransport();
Mail transport should be initialized one time during creating di container (see initialization PrismaClient in backend/src/secondary-adapters/postgres/postgres-container-module.ts)

2022-08-09 11:45 UTC, VitaliiBedletskyi commented on backend/src/configuration/mail-transport.ts
> +import { CONFIG } from './config';
Better to move it to backend/src/secondary-adapters/mail/mail-transport.ts

2022-08-09 11:45 UTC, VitaliiBedletskyi commented on backend/src/core/mail/application/mail-service.ts
> +export class MailService {
It should be the `MailAdapter` in `src/secondary-adapters/mail/` that implements port (Interface) MailAdapterInterface. Create `MailAdapterInterface` in `backend/src/core/common`. As a result, all our services from the application level will depend only on `MailAdapterInterface` and don't know anything about realization mail sending

2022-08-09 11:45 UTC, VitaliiBedletskyi commented on backend/src/core/mail/mail-container-module.ts
> +  bind<MailService>(CONTAINER_TYPES.MailService).to(MailService);
Should bind `MailAdapterInterface` to `MailAdapter` which I wrote above...

2022-08-09 17:25 UTC, nemuzora-nozomu commented
I created separate mail repository like the user one, and moved mail transport to secondary adapter. to be honest I'm not 100% sure if I did the binding right since I haven't done this before and I don't have any proper ways to test it out at the moment.

2022-08-09 18:24 UTC, nemuzora-nozomu commented
gonna create test route to ensure that the service works first, I'll drop commits tomorrow

2022-08-09 18:33 UTC, VitaliiBedletskyi requested changes

2022-08-09 18:33 UTC, VitaliiBedletskyi commented on backend/src/core/mail/application/mail-service.ts
> +export class MailService {
As I understood to send mail you don't require to use MailService, just enough MailRepositoryAdapter, or is it some example? If it usage example please add a comment before the class declaration.

2022-08-09 18:33 UTC, VitaliiBedletskyi commented on backend/src/secondary-adapters/mail/mail-transport.ts
> +const mailTransport = new AsyncContainerModule(async (bind: interfaces.Bind) => {
Create separate mail-container-module.ts and move AsyncContainerModule to him.

2022-08-09 18:33 UTC, VitaliiBedletskyi commented on backend/src/secondary-adapters/mail/mail-transport.ts
> +  const transport = nodemailer.createTransport({
Leave the logic to initialize mail transport in this file

2022-08-10 17:38 UTC, VitaliiBedletskyi commented
Hi, could you please fix remarks and resolve merge conflicts?

2022-08-11 08:21 UTC, VitaliiBedletskyi approved these changes

2022-08-11 08:22 UTC, merged