Task/common109 show real subscriptions
BinaryStudioAcademy/bsa-2022-streamlet pull request #176
Opened 2022-08-29 20:37 UTC by foxt451

Approximate work done within the scope of this PR:
- display real subscriptions in sidebar
- display "No subscriptions yet" if no subscriptions yet
- add subscription functionality to video page
- fix the following issue: subscriptions block is not displayed on small screens when collapsed menu is opened by pressing the burger button
The subscription state should be synchronized between Channel page, Video page and Sidebar, and should persist upon page refresh.

2022-08-29 20:38 UTC, foxt451 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Subscription logic](https://trello.com/c/6ZdYxQqH/109-implement-subscription-logic)

2022-08-30 06:45 UTC, ihor-pavliuk requested changes

2022-08-30 06:45 UTC, shirokuronemuri commented on backend/core/src/core/channel-subscription/application/channel-subscription-service.ts
> +  }> {
I think you should create a separate type here

2022-08-30 09:42 UTC, ihor-pavliuk approved these changes

2022-08-30 09:42 UTC, merged