Task/backend204 implement replies for comment
BinaryStudioAcademy/bsa-2022-streamlet pull request #209
Opened 2022-09-03 20:38 UTC by artem-drozdov

2022-09-03 20:39 UTC, artem-drozdov commented
![](https://github.trello.services/images/mini-trello-icon.png) [The preview from the previous video page is displayed after opening the new video page](https://trello.com/c/G7FSYZUM/247-the-preview-from-the-previous-video-page-is-displayed-after-opening-the-new-video-page)

2022-09-03 20:39 UTC, artem-drozdov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement the possibility to comment the comments of other users on the Video page](https://trello.com/c/0om6bEPz/204-implement-the-possibility-to-comment-the-comments-of-other-users-on-the-video-page)

2022-09-03 21:22 UTC, WanderningMaster requested changes

2022-09-03 21:22 UTC, WanderningMaster commented on backend/core/prisma/schema.prisma
> +  parentId         String?
optional string columns should be non-null and defaulted to (""), see comments in scheme.prisma file

2022-09-03 21:22 UTC, WanderningMaster commented on backend/core/src/secondary-adapters/postgres/video/video-repository-adapter.ts
> +    const commentsWithReplies = await Promise.all(
I guess its better to use prisma transaction api in this case

2022-09-04 16:35 UTC, WanderningMaster approved these changes

2022-09-04 16:36 UTC, merged