Task/frontend29 configure notifications
BinaryStudioAcademy/bsa-2022-streamlet pull request #47
Opened 2022-08-14 13:06 UTC by ihor-pavliuk

2022-08-14 14:19 UTC, ihor-pavliuk commented
![](https://github.trello.services/images/mini-trello-icon.png) [Configure notifications](https://trello.com/c/s7pWDKVC/29-configure-notifications)

2022-08-15 15:28 UTC, kyrylo-burmelov requested changes
Let me know if you have any questions

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/common/header/header.module.scss
> +    top: 0%;
Not a mistake, but you can use here `top: 0` without `%`

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/common/header/header.tsx
> +import { NotificationDropdown } from 'components/notification-dropdown/notification-dropdown';
import order, you have empty line before styles import, so this has to be above styles

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/common/header/header.tsx
> +                {haveUnreadNotifications && <div className={styles['unread-mark']}></div>}
you can use self-closing tags in such cases

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/common/header/header.tsx
> +                    }`}
use clsx for managing classNames, see more here https://www.npmjs.com/package/clsx

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +    <Link className={styles['link']} to={`/video/${notification.videoId}`}>
Does it mean that every notification has link to a video page? That's incorrect

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +        <div className={`${styles['status']} ${!notification.isViewed && styles['status-unread']}`}></div>
again clsx

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +            {notification.username} has started streaming: {notification.videoName}
Notification body must be generic

2022-08-15 15:28 UTC, kyrylo-burmelov commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +        <img src={notification.videoPreview} className={styles['thumbnail']} alt="channel-avatar" width="60" />
Not all notifications would have an image, it has to be optional

2022-08-15 15:30 UTC, kyrylo-burmelov commented on frontend/src/components/common/header/header.tsx
> +                    }`}
```
className={clsx(styles['notifications-wrapper'], { ["is-active"]: true })}
```

2022-08-20 14:43 UTC, ihor-pavliuk commented on frontend/src/components/common/header/header.module.scss
> +    top: 0%;
fixed

2022-08-20 14:44 UTC, ihor-pavliuk commented on frontend/src/components/common/header/header.tsx
> +import { NotificationDropdown } from 'components/notification-dropdown/notification-dropdown';
fixed

2022-08-20 15:08 UTC, ihor-pavliuk commented on frontend/src/components/common/header/header.tsx
> +                {haveUnreadNotifications && <div className={styles['unread-mark']}></div>}
fixed

2022-08-20 15:09 UTC, ihor-pavliuk commented on frontend/src/components/common/header/header.tsx
> +                    }`}
couldn't make it work so I rewrote it in different way

2022-08-20 15:09 UTC, ihor-pavliuk commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +    <Link className={styles['link']} to={`/video/${notification.videoId}`}>
fixed

2022-08-20 15:09 UTC, ihor-pavliuk commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +        <div className={`${styles['status']} ${!notification.isViewed && styles['status-unread']}`}></div>
rewritten

2022-08-20 15:09 UTC, ihor-pavliuk commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +            {notification.username} has started streaming: {notification.videoName}
done

2022-08-20 15:10 UTC, ihor-pavliuk commented on frontend/src/components/notification-dropdown/components/notification/notification.tsx
> +        <img src={notification.videoPreview} className={styles['thumbnail']} alt="channel-avatar" width="60" />
done

2022-08-20 15:20 UTC, ihor-pavliuk commented
sorry for refactoring so much code ;;

2022-08-21 08:44 UTC, so5tmaker approved these changes

2022-08-21 09:32 UTC, artem-drozdov approved these changes

2022-08-21 14:17 UTC, kyrylo-burmelov approved these changes
Really bad that you have so many updates that's not related to your task. It's hard to review PR. Next time please create separate tasks for huge refactoring updates that's not related to your task.

2022-08-21 14:17 UTC, merged