Task/infrastructure21 configure rabbitmq
BinaryStudioAcademy/bsa-2022-streamlet pull request #5
Opened 2022-08-08 11:51 UTC by WanderningMaster

2022-08-08 11:52 UTC, WanderningMaster commented
![](https://github.trello.services/images/mini-trello-icon.png) [Configure RabbitMQ](https://trello.com/c/N8PvUoz6/21-configure-rabbitmq)

2022-08-08 12:34 UTC, VitaliiBedletskyi commented
Needs also create a port (Interface) and at least one adapter which implements the described interface for simple use in the application.

2022-08-08 17:06 UTC, VitaliiBedletskyi requested changes

2022-08-08 17:06 UTC, VitaliiBedletskyi commented on backend/src/secondary-adapters/amqp/amqp-container-module.ts
> +import amqp, { Channel } from 'amqplib';
Better to use connect method from destructured import

2022-08-08 17:06 UTC, VitaliiBedletskyi commented on backend/src/core/user/port/amqp-channel.ts
> +import { AmqpSendToQueueDto, AmqpConsumeDto } from 'shared/build';
Move to backend/src/core/common/port/amqp-channel.ts

2022-08-09 09:33 UTC, VitaliiBedletskyi requested changes

2022-08-09 09:33 UTC, VitaliiBedletskyi commented on .docker/docker-compose.yml
> +  rabbitmq:
Should also add the rabbitmq container to docker-compose.dev.yml and ocker-compose.local.yml files

2022-08-09 11:46 UTC, VitaliiBedletskyi approved these changes

2022-08-09 11:46 UTC, merged