Fix/frontend40 sidebar studio
BinaryStudioAcademy/bsa-2022-streamlet pull request #52
Opened 2022-08-15 06:44 UTC by so5tmaker

2022-08-15 06:49 UTC, so5tmaker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement sidebar component in studio app](https://trello.com/c/zg6s8Grx/40-implement-sidebar-component-in-studio-app)

2022-08-16 07:59 UTC, kyrylo-burmelov requested changes
Review is ready) Let me know if you have any questions

2022-08-16 07:59 UTC, kyrylo-burmelov commented on frontend/src/components/studio/sidebar/sidebar.tsx
> +        <Link to={item.routeName as AppRoute}>
https://en.reactjs.org/docs/lists-and-keys.html

2022-08-16 07:59 UTC, kyrylo-burmelov commented on frontend/src/components/studio/sidebar/sidebar.tsx
> +  const getColor = (item: string): string => (pathname === item ? IconColor.GREEN : IconColor.WHITE);
Not understandable enough. Better to do it in thie way:

```
const isActiveTab = ...

// then add the color using isActiveTab var 
```

2022-08-16 07:59 UTC, kyrylo-burmelov commented on frontend/src/components/studio/sidebar/sidebar.tsx
> +  const getColor = (item: string): string => (pathname === item ? IconColor.GREEN : IconColor.WHITE);
In addition, your solution will not work when you have bigger route name. Like:

`/home/route-name/route-name`

2022-08-16 07:59 UTC, kyrylo-burmelov commented on .stylelintrc.yml
> +  scss/at-rule-no-unknown: true
As we discussed in slack. Try to get rid of that and use extends scss. Let me know if it does not work

2022-08-17 20:05 UTC, kyrylo-burmelov approved these changes

2022-08-17 20:05 UTC, merged