Task/frontend41 create video chat component
BinaryStudioAcademy/bsa-2022-streamlet pull request #62
Opened 2022-08-17 12:43 UTC by artem-drozdov

2022-08-17 12:43 UTC, artem-drozdov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement video chat component](https://trello.com/c/jSDnMYJT/41-implement-video-chat-component)

2022-08-17 12:48 UTC, kyrylo-burmelov requested changes

2022-08-17 12:48 UTC, kyrylo-burmelov commented on shared/src/common/types/comment/index.ts
> +  date_added: string;
use camel case. `date_added`

2022-08-17 12:48 UTC, kyrylo-burmelov commented on frontend/src/components/video-chat/video-comment/video-comment.tsx
> +import './video-comment.scss';
use module scss

2022-08-17 12:48 UTC, kyrylo-burmelov commented on frontend/src/components/video-chat/video-comment/video-comment.scss
> +  color: #ffffff;
all colors must be variables

2022-08-17 12:48 UTC, kyrylo-burmelov commented on frontend/src/components/common/send-message/send-message.tsx
> +          </svg>
move svg's to icon component

2022-08-17 12:48 UTC, kyrylo-burmelov commented on frontend/src/assets/css/styles.scss
> +}
why it's global styles?

2022-08-17 20:02 UTC, kyrylo-burmelov requested changes

2022-08-17 20:02 UTC, kyrylo-burmelov commented on frontend/src/components/common/send-message/send-message.tsx
> +};
- each input must have controlled state (can be in a component)
- each button must have on click handler in a container (you can leave action empty, no need to add redux state for now)

2022-08-17 20:02 UTC, kyrylo-burmelov commented on frontend/src/components/video-chat/video-comment/video-comment.tsx
> +        <span className={styles['dispatch-time']}>{comment.dateAdded}</span>
you would probably have date timestamp from backend. Use dayjs to prepare date formatting https://day.js.org/

2022-08-17 20:02 UTC, kyrylo-burmelov commented on frontend/src/components/video-chat/video-comment/video-comment.tsx
> +        <img className={styles['commentators-avatar']} src={comment.avatar} alt={comment.name} />
Having in mind that user avatar is not required field. So some users do not have avatar. You need to handle that and have default icon when avatar does not exist

2022-08-19 09:55 UTC, kyrylo-burmelov approved these changes

2022-08-19 09:59 UTC, merged