Fix/frontend86 linking pages
BinaryStudioAcademy/bsa-2022-streamlet pull request #78
Opened 2022-08-20 19:07 UTC by Barracuda713

Add linking between the Main and the Sign-in pages:
- Sign Up -> Sign In
- Sign In (hasToken) -> getUser -> Root
- Sign In -> Root

Add "Confirm password" to Sign Up page

Add form inputs validation for Sign In, Sign Up & Restore password pages

2022-08-20 19:07 UTC, Barracuda713 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add linking between the Main and the Sign-in pages](https://trello.com/c/vaPKbvzd/86-add-linking-between-the-main-and-the-sign-in-pages)

2022-08-20 19:07 UTC, Barracuda713 commented
![](https://github.trello.services/images/mini-trello-icon.png) [The Sign-up page doesn't have the "Repeat password" input field](https://trello.com/c/RTR4DdsF/84-the-sign-up-page-doesnt-have-the-repeat-password-input-field)

2022-08-20 19:08 UTC, Barracuda713 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validation on frontend side for Sign-in / Sign-up + restore password](https://trello.com/c/p9kMwJt9/59-validation-on-frontend-side-for-sign-in-sign-up-restore-password)

2022-08-20 20:26 UTC, artem-drozdov commented on frontend/src/components/auth/components/sign-up-form/common.ts
> +  password_confirm: '',
use camelCase

2022-08-21 04:31 UTC, foxt451 requested changes

2022-08-21 04:31 UTC, foxt451 commented on frontend/src/components/app/app.tsx
> +
if I understand correctly, this dispatch will work twice (user is null initially, then the user changes in the reducer and useEffect works twice)

2022-08-21 04:31 UTC, foxt451 commented on frontend/src/components/auth/components/form-controls.module.scss
> +  box-shadow: 0 0 3px 0 rgb(244 27 59 / 80%), 0 0 5px 0 rgb(244 27 59 / 50%);
I guess you could take this color into a variable (and apply sass's color modification function to change opacity, if you like)

2022-08-21 06:10 UTC, foxt451 approved these changes, later dismissed

2022-08-21 09:30 UTC, artem-drozdov submitted a review, later dismissed

2022-08-21 17:56 UTC, artem-drozdov approved these changes

2022-08-22 06:52 UTC, merged