Fix/frontend78 search page
BinaryStudioAcademy/bsa-2022-streamlet pull request #79
Opened 2022-08-20 19:27 UTC by Barracuda713

2022-08-22 06:24 UTC, foxt451 requested changes

2022-08-22 06:24 UTC, foxt451 commented on frontend/src/components/search/components/video-card/styles.module.scss
> +  background-color: rgb(0 0 0 / 70%);
add the color to variables

2022-08-22 06:24 UTC, foxt451 commented on frontend/src/components/search/components/video-card/styles.module.scss
> +  background-color: rgb(255 255 255 / 25%);
add the color to variables

2022-08-22 06:24 UTC, foxt451 commented on frontend/src/components/search/components/video-card/styles.module.scss
> +  background-color: rgb(255 255 255 / 15%);
add the color to variables

2022-08-22 06:24 UTC, foxt451 commented on frontend/src/components/search/components/video-card/styles.module.scss
> +  background-color: rgb(255 255 255 / 25%);
add the color to variables

2022-08-22 06:24 UTC, foxt451 commented on frontend/src/components/search/search.tsx
> +    // eslint-disable-next-line
it doesn't seem right

2022-08-23 10:15 UTC, Barracuda713 commented
Due to a lot of merge conflicts and almost completely updated header component, 
I decided to close this PR and make a new one with uptodate components.

2022-08-23 10:15 UTC, closed without merging