Task/common94 finalize auth
BinaryStudioAcademy/bsa-2022-streamlet pull request #81
Opened 2022-08-21 12:11 UTC by foxt451

This branch finalizes the auth flow without Google auth, i.e.: account verification and password restoration, including improvements and bug fixes from previous branches. This branch incorporates Barracuda713's task for frontend validation and my previous task for backend validation improvement.

2022-08-21 12:15 UTC, foxt451 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Finalize authorization flow](https://trello.com/c/0x0tjKTN/94-finalize-authorization-flow)

2022-08-21 12:29 UTC, foxt451 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add separate secrets for Access and Refresh tokens](https://trello.com/c/fhtFVhXF/75-add-separate-secrets-for-access-and-refresh-tokens)

2022-08-21 15:10 UTC, Barracuda713 requested changes

2022-08-21 15:10 UTC, Barracuda713 commented on frontend/src/pages/account-verification-page/account-verification-confirm-page.tsx
> +          durationMs: 10_000,
Move it and other notification objects to auth/config/config.ts

2022-08-21 15:40 UTC, Barracuda713 approved these changes, later dismissed

2022-08-22 05:02 UTC, Barracuda713 approved these changes

2022-08-22 05:40 UTC, foxt451 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validation on back-end side for Sign-in / Sign-up + restore password](https://trello.com/c/pGBuAZ4a/61-validation-on-back-end-side-for-sign-in-sign-up-restore-password)

2022-08-22 06:56 UTC, kyrylo-burmelov approved these changes

2022-08-22 06:56 UTC, merged