Task/frontend44 channel page
BinaryStudioAcademy/bsa-2022-streamlet pull request #91
Opened 2022-08-23 11:59 UTC by foxt451

This is the first part of the task. The remaining part is to add functionality for subscribe button and probably fix some bugs. Also, pagination is missing, but it's beyond the scope of this task

2022-08-23 12:11 UTC, foxt451 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement channel page](https://trello.com/c/a0wOJwYL/44-implement-channel-page)

2022-08-23 14:17 UTC, serhii-hnidobor requested changes

2022-08-23 14:17 UTC, ghost commented on backend/core/src/primary-adapters/rest/channel-crud/channel-crud-controller.ts
> +};
for helper we have folder core/shared/helpers it would be better to move it there

2022-08-23 14:17 UTC, ghost commented on shared/src/validation-schemas/user/user-sign-up.validation-schema.ts
> +    .lowercase()
reductant i already fix this bug on backend side see https://github.com/BinaryStudioAcademy/bsa-2022-streamlet/pull/90

2022-08-23 14:17 UTC, ghost commented on frontend/src/store/root-reducer.ts
> +import { reducer as channelPage } from './channel-page/reducer';
in my opinion, it is better to call it just a channel because channelPage sounds like a component

2022-08-23 14:17 UTC, ghost commented on frontend/src/pages/channel-page/components/about-section/about-section.tsx
> +  authorNameDisplay = authorNameDisplay + (combinedFirstLastName ? ` (${combinedFirstLastName})` : '');
I think it's better to put it in the helper because other components may need it

2022-08-23 18:44 UTC, WanderningMaster requested changes

2022-08-23 18:44 UTC, WanderningMaster commented on backend/core/prisma/seed-data/videos.ts
> +const videosNoChannels: Omit<Video, 'updatedAt' | 'createdAt' | 'channelId' | 'poster' | 'durationSec'>[] = [
better move it into separate type

2022-08-24 17:17 UTC, WanderningMaster submitted a review, later dismissed

2022-08-24 22:00 UTC, serhii-hnidobor submitted a review, later dismissed

2022-08-25 07:54 UTC, WanderningMaster approved these changes

2022-08-25 09:15 UTC, ghost approved these changes

2022-08-25 10:45 UTC, merged